name: build
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
          - ruby: 3.1
            gemfile: Gemfile
          - ruby: 3.1
            gemfile: gemfiles/Gemfile-6-1
          - ruby: '3.0'
            gemfile: Gemfile
          - ruby: '3.0'
            gemfile: gemfiles/Gemfile-6-1
          - ruby: 2.7
            gemfile: gemfiles/Gemfile-6-0
          - ruby: 2.6
            gemfile: gemfiles/Gemfile-5-2
    env:
      CI: 1
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      USE_OFFICIAL_GEM_SOURCE: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rails test
